### ISSUE TITLE
Problem when upgrading to 0.4.*

### ISSUE THREAD

**Issue by TheRealSlapshot** [ericpaulbishop/redmine_git_hosting#132]
Hello everybody,

I have a problem when trying to upgrade the plugin to any of the 0.4.*-Versions. I'm currently on 0.3.0 along with Redmine 1.2.1-stable. When trying rake db:migrate_plugins, I get the following error:

undefined method `notified_cia' for #Changeset:0x7f97296e4e58 

To explain a little bit more: I previously had the 0.1.0-version of this plugin. I didn't bother to update it until now. My first attempts to directly update to 0.4.2 fail with the error above. Then I tried the 0.4.0-update, since the notify-cia feature was introduced here, but with no other result. Fortunately, the 0.3.0-update succeeded. But the error still occurs when trying to update to 0.4.0.

Much appreciations for your help
TheRealSlapshot

**Comment by TheRealSlapshot** [comment]
No one got any solution? In the meantime, we also experience the problem mentioned in Issue #89. But as we can't update to 0.4.2, I cannot check, if the #89-problem is cleared for us with the current version.

**Comment by xrogaan** [comment]
You need to remove all the existing repositories.
